name: Auto Assign PRs

on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Assign PR to reviewers and assignees
        uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          configuration-path: .github/auto_assign.yml
