on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR based on labels
        uses: kentaro-m/auto-assign-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: 'reviewer1, reviewer2'  # Default assignees if no labels are present
          labels: 'frontend, backend, bug'  # Define the labels that will trigger assignments
          teams: 'frontend-team, backend-team'  # GitHub teams that will be assigned based on label




















