name: Auto-Assign PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-assign PR based on labels
        uses: mheap/github-action-auto-assign@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: '.github/auto-assign.yml'
